# Generated by Django 5.0.7 on 2024-07-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('closed_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('wait', 'Waiting for executor'), ('in_process', 'In process'), ('finished', 'Finished')], default='wait', max_length=10)),
                ('report', models.TextField()),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_tasks', to='profiles.profile')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='profiles.profile')),
            ],
        ),
    ]
