# Generated by Django 5.0.7 on 2024-07-15 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='no title', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='closed_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_tasks', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
