# Generated by Django 5.0.7 on 2024-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_description_task_title_alter_task_closed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
