# Generated by Django 5.0.7 on 2024-07-22 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user'),
        ('tasks', '0003_alter_task_closed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='orderer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='profiles.profile'),
        ),
    ]
